### PR TITLE
updatedsolinksshowup

### PR DESCRIPTION
**Pull request by SamyWarnants**
Fixed some errors and trying to commit properly now

### CODE REVIEW

**Review by RunningZeus5334 — COMMENTED** [review]
Just a litle fix and then u can merge :D

**Review by RunningZeus5334 — APPROVED** [review]
Looking good to me :D

**Comment by SamyWarnants** [comment]
There were some things I forgot on the about page that needed updates

**Review by TheNeg0t1ator — APPROVED** [review]
LGTM

**Pull request merged**
